# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-24 21:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login_app', '0011_auto_20171220_1844'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=255)),
                ('added_by', models.CharField(max_length=255)),
                ('start_date', models.DateField(null=True, verbose_name=['%b-%d-%Y'])),
                ('created_at', models.DateField(auto_now_add=True, null=True, verbose_name=['%b-%d-%Y'])),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wish_maker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wish_maker', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_app.User')),
                ('wishes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wish_list_app.Wish')),
            ],
        ),
        migrations.AddField(
            model_name='wish',
            name='users',
            field=models.ManyToManyField(related_name='wishes', through='wish_list_app.Wish_maker', to='login_app.User'),
        ),
    ]
